name: RDP to Azure VM

on: [push]

env:
  AZURE_RG: "your_resource_group_name"
  AZURE_VM: "your_vm_name"
  RDP_PORT: "3389"
  AZURE_REGION: "southeastasia"

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          inlineScript: |
            Import-Module Az.Accounts -Force
            Import-Module Az.Resources -Force
            Import-Module Az.Compute -Force
            Set-AzContext -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get public IP address of the VM
        run: |
          ip=$(az network public-ip show --resource-group ${{ env.AZURE_RG }} --name ${{ env.AZURE_VM }}-PublicIP --query ipAddress -o tsv)
          echo "::set-output name=public_ip_address::$ip"

        id: public_ip_address

      - name: Open RDP connection to the VM
        run: |
          cmdkey /generic:TERMSRV/${{ steps.public_ip_address.outputs.public_ip_address }} /user:azureuser /pass:${{ secrets.AZURE_PASSWORD }}
          mstsc /v:${{ steps.public_ip_address.outputs.public_ip_address }}:${{ env.RDP_PORT }} /f
