- name: Set up RDP connection to Azure VM
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    resource_group_name: "your_resource_group_name"
    vm_name: "your_vm_name"
    rdp_port: 3389
    azure_region: "southeastasia"

  tasks:
    - name: Get public IP address of the VM
      azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}-PublicIP"
      register: public_ip_address_info

    - name: Open RDP connection to the VM
      command: "mstsc /v:{{ public_ip_address_info['publicipaddress']['ipAddress'] }}:{{ rdp_port }}"
      delegate_to: localhost
